### PR TITLE
Updated compiler for rc 6 and handlebars to 1.0 - 4

### PR DESCRIPTION
**Pull request by ryanmarc**
steedlefronts...

### CODE REVIEW

**Comment by jerodsanto** [comment]
@ryanmarc this looks almost all good, except it appears that you appended to `vendor/handlebars.js` instead of replacing the old one with the new one. This broke my build.

Was that an accident or did you have a reason to do it that way?

(I forked and made a [similar commit](https://github.com/Gocella/ember-handlebars-brunch/commit/4e1d9acae3fdfa6b5401dc75571240eef736592b) which worked for me here)

**Comment by ryanmarc** [comment]
No, that would be a mistake. I probably just messed it up when I was pasting the new content in. I'll update this commit in the morning.

**Comment by ryanmarc** [comment]
This has been fixed.

**Comment by bartsqueezy** [comment]
This plugin has now been updated to the latest version of ember.js - v1.0.0.  I've tagged every commit that points to a different version of ember.js.  This will follow standard practice by allowing the developer to choose which version of this plugin they want to include in their project.  Please update your `package.json` to reference the version of ember you want this plugin to pre-compile templates for (e.g. `1.0.0-rc.7`, `1.0.0-rc.8`, `1.0.0`, etc).

Sorry for the wait!

**Pull request closed without merging**
