### PR TITLE
Integration with toranb/ember-template-compiler

### PR DESCRIPTION
**Pull request by gcollazo**
I simplified the plugin's code without losing any functionality.

One advantage of this change is that [toranb/ember-template-compiler](https://github.com/toranb/ember-template-compiler) is referencing [handlebars npm package](https://npmjs.org/package/handlebars), so it should be much easier to keep things up to date. Also this [repo](https://github.com/toranb/ember-template-compiler) is using the [ember-template-compiler.js](https://github.com/toranb/ember-template-compiler/blob/master/vendor/ember-template-compiler.js) which is also used by [ember-app-kit](https://github.com/stefanpenner/ember-app-kit) a somewhat official thing.

Also:
- Removed all unnecessary files after changing to toranb/ember-template-compiler
- Fixed tests
- Added travis integration
- Updated package.json dependencies

Is this cool?

### CODE REVIEW

**Comment by mutewinter** [comment]
:+1:  love this. Awesome job @gcollazo

**Comment by mutewinter** [comment]
Just tried this out in my own Ember app and it compiled templates flawlessly.

**Comment by zxaos** [comment]
This is working for me too. It seems to bypass the #12 (and by extension #13 ) issues as well.

**Comment by gcollazo** [comment]
@bartsqueezy got any feedback on this?

**Comment by bartsqueezy** [comment]
Sorry for the delayed response everyone and for any inconveniences it has caused!

@gcollazo, this is exactly the direction I've been wanting to go with this plugin.  Thanks for putting in the time to work on this.  Before I merge, I first need to merge in other ember.js updates and tag this project accordingly so we can continue to provide a working environment based on the version of ember.js you're using within your brunch application.  I'll make time to do this over the next few nights.  Look forward to having this by end of this week!

**Comment by egaba** [comment]
:+1: this is awesome

**Comment by jas** [comment]
+1.  Would prefer this over #13 and #16.

**Comment by john-kurkowski** [comment]
+1

**Comment by gcollazo** [comment]
Just updated the ember-template-compiler dependency from "~1.2" to "~1.3"

**Comment by bartsqueezy** [comment]
@gcollazo, I've cherry picked the commits I felt were acceptable to merge.  As far as converting to use ember-template-compiler as a means of keeping the compiler file up-to-date, I decided to not include that change into this project.  I've added support to have npm control versioning of Handlebars.js, instead of relying on yet one more person to stay on top of upgrading.  Eventually, npm will control the versioning of the ember-template-compiler.js file as well by utilizing [components-ember](https://github.com/components/ember).  However, I had problems trying to reference the 1.2.0 tag while pulling in their project via npm.  Once another official ember release is processed, I'll start using them as a dependency.

Until then, this plugin has been upgraded to ember 1.2.0 and handlebars 1.1.2.  Thanks everyone for your feedback and contributions!

**Pull request closed without merging**
